### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by VesninEN** [amgine/gitter#16]
When updating from the Help menu, an error occurs after downloading the update
![2022-02-13_012006](https://user-images.githubusercontent.com/29756588/153730340-63d06a30-eb80-4242-983f-5cdc6e919f51.png)

**Comment by amgine** [comment]
Currently only versions starting from `1.0.26` can be updated automatically.  
`1.0.25` (and earlier) uses an old updater that got too hard to maintain, and there is no way to patch it automatically, so for `1.0.25-` manual update is required.  
`gitter.updater.exe` is expected to do nothing without any command line arguments.
