### ISSUE TITLE
Ошибка при попытке загрузки данных из внешнего репозитория

### ISSUE THREAD

**Issue by VesninEN** [amgine/gitter#20]
Date: 2024-10-09 23:13:18 +0300
Exception: System.FormatException
Message:
Один из идентифицированных элементов имел недопустимый формат.

Call Stack:
   в gitter.Git.AccessLayer.CLI.LogParser.StrictISO8601TimestampField.GetOffset()
   в gitter.Git.AccessLayer.CLI.LogParser.StrictISO8601TimestampField.GetValue()
   в gitter.Git.AccessLayer.CLI.LogParser.BuildRevision()
   в gitter.Git.AccessLayer.CLI.LogParser.Parse(ITextSegment textSegment)
   в gitter.Framework.CLI.AsyncTextParser.DecodeAndParse(Int32 bytesCount)
   в gitter.Framework.CLI.AsyncTextParser.OnStreamRead(IAsyncResult ar)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   в System.Threading.Tasks.Task.FinishContinuations()
   в System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   в System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   в System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

Loaded Assemblies:
gitter, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.fw, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.cli, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.fw, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.gui, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.gitlab, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.redmine, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.teamcity, Version=1.0.26.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
NHunspell, Version=1.2.5554.16953, Culture=neutral, PublicKeyToken=1ac793ea843b4366
[GAC] mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] mscorlib.resources, Version=4.0.0.0, Culture=ru, PublicKeyToken=b77a5c561934e089
[GAC] System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[GAC] System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[GAC] System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Windows.Forms.resources, Version=4.0.0.0, Culture=ru, PublicKeyToken=b77a5c561934e089
[GAC] System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

Возникает при двойном клике по одному из списка недавних репозиториев  

![image](https://github.com/user-attachments/assets/29433544-248c-49b2-96eb-f434fdb25b82)

**Comment by amgine** [comment]
формат даты/времении изменился в git v2.45 (https://github.com/git/git/commit/69e2bee1a3ba2f9367d55992f401e6365be100ea)
парсер был обновлен в gitter v1.1.5 (https://github.com/amgine/gitter/commit/d3b938c674130092a9ff0c125f02266caca3a2ba)
актуальная версия не должны иметь проблем с разбором strict ISO8601.

**Comment by VesninEN** [comment]
Отлично. А какую версию  из двух имеющихся качать (неясно как выбрать)?

[gitter-binaries.zip](https://github.com/amgine/gitter/releases/download/v1.1.5/gitter-binaries.zip)

[gitter-net6.0-binaries.zip](https://github.com/amgine/gitter/releases/download/v1.1.5/gitter-net6.0-binaries.zip)

**Comment by amgine** [comment]
без суффикса версия исторически основана на net48.
net6.0 вышел позже net48, соответственно в нем будет больше оптимизаций, и эта версия на данный момент более актуальная (поддержка DPI-режимов также лучше в net6.0).
net48 пока держится для поддержки старых ОС или других ситуаций, когда установка net6.0 невозможна.
работать так или иначе будут обе.
вероятно добавлю потом суффикс `legacy` для менее актуальных сборок.

**Comment by VesninEN** [comment]
[gitter-binaries.zip](https://github.com/amgine/gitter/releases/download/v1.1.5/gitter-binaries.zip) это net-5, net7, net8 , net9 или что-то другое?

**Comment by amgine** [comment]
это net48
