### ISSUE TITLE
NRE occured in Commit window when right-press on file in "Unstaged changes"

### ISSUE THREAD

**Issue by catahoc** [amgine/gitter#6]
![image](https://cloud.githubusercontent.com/assets/2704650/5425634/24baeb86-8331-11e4-9e0b-35868d28ac22.png)
Date: 2014-12-14 01:32:26 +0300
Exception: System.NullReferenceException
Message:
Ссылка на объект не указывает на экземпляр объекта.

Call Stack:
   в gitter.Git.IndexChangesDiffSource.Equals(Object obj)
   в gitter.Git.Gui.Views.DiffViewModel.Equals(Object obj)
   в gitter.Framework.Controls.ViewBase.set_ViewModel(Object value)
   в gitter.Framework.Controls.ViewDockService.ShowView(Guid guid, Object viewModel, Boolean activate)
   в gitter.Git.Gui.Views.GitViewBase.ShowContextualDiffView(IDiffSource diffSource)
   в gitter.Framework.Controls.CustomListBox.HandleItemDefaultMouseDown(Int32 itemIndex, MouseEventArgs e)
   в gitter.Framework.Controls.CustomListBox.OnMouseDown(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
gitter, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.fw, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.cli, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.fw, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.git.gui, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.redmine, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
gitter.teamcity, Version=1.0.16.0, Culture=neutral, PublicKeyToken=1878ea6221b2e3a7
NHunspell, Version=1.1.1.0, Culture=neutral, PublicKeyToken=1ac793ea843b4366
[GAC] mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] mscorlib.resources, Version=4.0.0.0, Culture=ru, PublicKeyToken=b77a5c561934e089
[GAC] System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[GAC] System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[GAC] System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[GAC] System.Windows.Forms.resources, Version=4.0.0.0, Culture=ru, PublicKeyToken=b77a5c561934e089
[GAC] System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by amgine** [comment]
should be fixed in v1.0.17
